[[fonts]]
name = "ANAKRON"
font_size = 12

[fonts.chars]
width = 40

[fonts.clrs]
bg = "#000000"
fg = "#ffffff"
base = [
  "#000000",
  "#aa0000",
  "#00aa00",
  "#ffaa00",
  "#0000aa",
  "#aa00aa",
  "#00aaaa",
  "#aaaaaa",
  "#555555",
  "#ff5555",
  "#55ff55",
  "#ffff00",
  "#00aaff",
  "#ff55ff",
  "#55ffff",
  "#ffffff",
]

[[fonts.gens]]
name = "sample"
txts = [
  "prog",
  "eng",
  "multi",
  "c64basic",
  "fortran",
  "pascal",
  "c",
  "apl",
  "bqn",
  "uiua",
  "box",
]

[[fonts.gens]]
name = "all"
txts = ["header", "sample"]
