[ANAKRON]
font_size = 12

[ANAKRON.chars]
width = 40

[ANAKRON.clrs]
bg = "#000000"
fg = "#ffffff"
base = [
  "#000000",
  "#aa0000",
  "#00aa00",
  "#ffaa00",
  "#0000ff",
  "#aa00aa",
  "#00aaaa",
  "#aaaaaa",
  "#555555",
  "#ff5555",
  "#55ff55",
  "#ffff00",
  "#00aaff",
  "#ff55ff",
  "#55ffff",
  "#ffffff",
]

[ANAKRON.gens]
sample = [
  "prog",
  "eng",
  "multi",
  "fortran",
  # "engalt",
  # "pretty",
  # "math",
  # "box",
  # "braille",
]
all = ["header", "sample"]
