[ANAKRON]
xs = [2, 3]
zip_includes = ["README.md", "LICENSE", "AUTHORS"]
x_format = "{name}_{x}x"
ttfix = '''
f.os2_version = 4
f.os2_vendor = "BenP"
f.os2_panose = (2, 0, 6, 9, 0, 0, 0, 0, 0, 0)
f.os2_weight_width_slope_only = True
'''

[ANAKRON.sfnt]
"UniqueID" = "molarmanful: anakron: 2024"
"Vendor URL" = "https://github.com/molarmanful/anakron"
"Designer" = "Benjamin Pang"
"Designer URL" = "https://benpa.ng"
"License" = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
"License URL" = "https://scripts.sil.org/OFL"
