[ANAKRON]
font_size = 12

[ANAKRON.clrs]
bg = "#000000"
fg = "#ffffff"

base = [
  "#000000",
  "#aa0000",
  "#00aa00",
  "#aa5500",
  "#0000aa",
  "#aa00aa",
  "#00aaaa",
  "#aaaaaa",

  "#555555",
  "#ff5555",
  "#55ff55",
  "#ffff55",
  "#5555ff",
  "#ff55ff",
  "#55ffff",
  "#ffffff",
]

[ANAKRON.gens]
sample = [
  "prog",
  "eng",
  "multi",
  "scala",
  "clojure",
  "go",
  "svelte",
  "apl",
  "engalt",
  "pretty",
  "math",
  "box",
  "braille",
]
all = ["header", "sample"]
