---
name: pub
on:
  push:
    tags: ['*']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: echo -n ${{ github.ref_name }} > VERSION
      - run: nix build .#anakron-release
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: VERSION
          commit_message: bump to ${{ github.ref_name }}
      - name: release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: result/share/fonts/*
          file_glob: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          name: "molarmanful/ANAKRON"
          tag: "${{ inputs.tag }}"
          include-output-paths: true
