---
name: pub
on:
  push:
    tags: ['*']
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  pub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
      - run: echo -n ${{ github.ref_name }} > VERSION
      - uses: docker/setup-buildx-action@v3
      - uses: nixbuild/nix-quick-install-action@v29
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#anakron-release
      - name: release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: result/share/fonts/*
          file_glob: true
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: VERSION
